HW-3_1-JUNIT_EXTENSIONS_CALLBACK
aqa-dimqa/niffler-ng-6 pull request #2
Opened 2024-09-30 00:49 UTC by arrnel

2024-09-30 01:13 UTC, arrnel commented on niffler-e-2-e-tests-hw/src/test/java/guru/qa/niffler/api/CategoryApiClient.java
> +    @SneakyThrows
Забыл убрать

2024-09-30 01:15 UTC, arrnel commented on niffler-e-2-e-tests-hw/src/test/java/guru/qa/niffler/api/CategoryApiClient.java
> +    @SneakyThrows
Забыл убрать @SneakyThrows

2024-10-01 22:00 UTC, sashkir7 requested changes
Доброй ночи

Крайне тяжело проверять, когда:
1. В PR добавлено 80+ новый файлов (4к кода)
2. Плюс с этим при выполнении дз используется "творческий подход", то есть нестандартное решение (это про рабоут с UserModel)

В комменатриях подсветил ряд моментов, которые увидел. 
Просьба пройтись по ним и поправить. Также просьба вынести отдельный PR, в котором будет код, который относится непосредственно к текущей ДЗ

2024-10-01 22:00 UTC, sashkir7 commented on niffler-e-2-e-tests-hw/src/test/java/guru/qa/niffler/api/SpendApi.java
> +    );
Форматирование. 
Запятая не переносится на новую строку

2024-10-01 22:00 UTC, sashkir7 commented on niffler-e-2-e-tests-hw/src/test/java/guru/qa/niffler/enums/HttpStatus.java
> +public class HttpStatus {
Не всегда нужно сразу же выносить все возможные варианты
Иногда стоит придерживаться практики: понадобилось - добавил (то есть исходить из того, что пишет только тот код, который используем. Не забегаем наперед)

2024-10-01 22:00 UTC, sashkir7 commented on niffler-e-2-e-tests-hw/src/test/java/guru/qa/niffler/jupiter/annotation/Category.java
> +    boolean notGenerateName() default false;
Как по мне, то данное поле лишнее. Можно исходить из логики, если name = "", то генерить случайное название категории. Иначе - брать значение из аннотации

2024-10-01 22:00 UTC, sashkir7 commented on niffler-e-2-e-tests-hw/src/test/java/guru/qa/niffler/jupiter/annotation/Category.java
> +    boolean notGenerateIsArchived() default true;
Это поле я бы также удалил
После теста просто всегда переводить категорию в архив (далее будем удалять через БД)

2024-10-01 22:00 UTC, sashkir7 commented on niffler-e-2-e-tests-hw/src/test/java/guru/qa/niffler/jupiter/extension/CategoryExtension.java
> +                            .get(context.getUniqueId(), UserModel.class);
На данной домашней работе еще никакой работы с user(ом) не было

2024-10-01 22:00 UTC, sashkir7 commented on niffler-e-2-e-tests-hw/src/test/java/guru/qa/niffler/jupiter/extension/CategoryExtension.java
> +                            .get(context.getUniqueId(), UserModel.class);
Если работаете с пользователем через аннотацию, то в аннотации User добавьте поля категории и трат (в виде массивов). Такая структура будет более правильной (в след уроках об этом будет)

2024-10-01 22:00 UTC, sashkir7 commented on niffler-e-2-e-tests-hw/src/test/java/guru/qa/niffler/jupiter/extension/CategoryExtension.java
> +                            .get(context.getUniqueId(), UserModel.class);
Сохраняем пользователя, полученного из store в переменную, чтобы вывести в лог?
А далее в метод getUsernameOrThrowException() опять запрашиваем пользователя из store? Почему значение из переменной не передать?

2024-10-01 22:00 UTC, sashkir7 commented on niffler-e-2-e-tests-hw/src/test/java/guru/qa/niffler/jupiter/extension/CategoryExtension.java
> +    }
Если честно, то довольно нетривиальная логика
Можно сделать сильно проще. Не сильно понимаю, для чего так усложнять
PS. Советую отрефакторить и упростить код. Пример "как надо и красиво" - будет в след. уроках

2024-10-01 22:00 UTC, sashkir7 commented on niffler-e-2-e-tests-hw/src/test/java/guru/qa/niffler/jupiter/extension/CategoryExtension.java
> +    }
Можно просто достать категорию из store (а она там всегда должна быть) - и в каждом первом случае перевести ее в архивный статус (даже если она уже в архиве - чтобы обойти кейсы, когда мы меняем статус категории через UI)

2024-10-01 22:00 UTC, sashkir7 commented on niffler-e-2-e-tests-hw/src/test/java/guru/qa/niffler/jupiter/extension/DeleteSpendingExtension.java
> +}
Если хотим удалять трату, то не нужно для этого создавать отдельный extension. Есть уже расширение, которое работает с тратой - эту логику нужно добавить туда же (при необходимости). Состояние кода сейчас выглядит так, что можно данный класс полностью удалить

2024-10-01 22:00 UTC, sashkir7 commented on niffler-e-2-e-tests-hw/src/test/java/guru/qa/niffler/jupiter/extension/SpendingExtension.java
> +public class SpendingExtension implements BeforeEachCallback, AfterEachCallback, ParameterResolver {
Здесь, в целом, комментарии те же, что и в CategoryExtension. 
Сильно усложнено, как по мне

2024-10-01 22:00 UTC, sashkir7 commented on niffler-e-2-e-tests-hw/src/test/java/guru/qa/niffler/jupiter/extension/SpendingExtension.java
> +    private boolean categoryWasArchivedBefore = false;
На уровне extension-класса нельзя хранить изменяемые свойства, тк экземпляр extenison-класса Junit(ом) создается в ед. экземпляре. Именно из-за этого данные мы передаем через хранилище (store)

2024-10-01 22:00 UTC, sashkir7 commented on niffler-e-2-e-tests-hw/src/test/java/guru/qa/niffler/page/people/FriendsPage.java
> +}
Для чего подобные классы? 
Сразу же удалять. Меньше кода - меньше проблем

2024-10-01 22:00 UTC, sashkir7 commented on niffler-e-2-e-tests-hw/src/test/java/guru/qa/niffler/page/people/FriendsPage.java
> +}
Везде - по аналогии

2024-10-07 11:37 UTC, closed without merging